version: '3'

networks:
  iris-api-net:
    driver: bridge

services:

  iris-api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - iris-api-net

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    networks:
      - iris-api-net
    environment:
      - TZ=Europe/Paris
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yaml



  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - iris-api-net
    env_file:
        - .env
    volumes:
      - ./grafana:/var/lib/grafana
      - ./grafana-provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana


volumes:
  prometheus_data:
  grafana_data: