version: '3'

networks:
  iris-api-net:
    driver: bridge

services:

  iris-api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - iris-api-net

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    networks:
      - iris-api-net
    environment:
      - TZ=Europe/Paris
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yaml
  
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources

volumes:
  prometheus_data:
 