global:
  scrape_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'services'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['prometheus:9090', 'iris-api:8081']

  - job_name: 'azure-container-app'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['https://groupe4containerapp.happysea-c98f171c.francecentral.azurecontainerapps.io']  #azure container application URL