name: Projet Build and Publish Docker Image 

on:
  push:
    branches:
      - main

env:
  TEST_FULL_ACR_NAME: ${{ secrets.REGISTRY_LOGIN_SERVER }}
  TEST_IMAGE_REPOSITORY: github-actions/container-app
  
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/projetirisgroupe4:${{ github.sha }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/projetirisgroupe4:${{ github.sha }}

        - name: Build and deploy Container App
          uses: azure/container-apps-deploy-action@v2
          with:
            appSourcePath: ${{ github.workspace }}/src
            acrName: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            containerAppName: Groupe4Container-app
            resourceGroup: ${{ secrets.RESOURCE_GROUP }}
            imageToDeploy: ${{ secrets.REGISTRY_LOGIN_SERVER }}/projetirisgroupe4:${{ github.sha }}
            location: 'france central'
            ports: 8081
            dns-name-label: projetirisgroupe4
