name: Projet Build and Publish Docker Image 

on:
  push:
    branches:
      - main

  
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main

        - name: 'Hadolint for check the code' 
          uses: hadolint/hadolint-action@v3.1.0
          with:
              dockerfile: ./Dockerfile 
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}


        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/projetirisgroupe4:${{ github.sha }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/projetirisgroupe4:${{ github.sha }}

        - name: Build and deploy Container App
          uses: azure/container-apps-deploy-action@v1
          with:
            acrName: efreibigdata
            containerAppEnvironment : groupe4containerapp
            containerAppName: groupe4containerapp
            resourceGroup: ${{ secrets.RESOURCE_GROUP }}
            imageToDeploy: ${{ secrets.REGISTRY_LOGIN_SERVER }}/projetirisgroupe4:${{ github.sha }}
            location: 'france central'
            targetPort: 8081
            registryUsername: ${{ secrets.REGISTRY_USERNAME }}
            registryPassword: ${{ secrets.REGISTRY_PASSWORD }}
            acrUsername: ${{ secrets.REGISTRY_USERNAME }}
            acrPassword: ${{ secrets.REGISTRY_PASSWORD }}
            azureCredentials : ${{ secrets.AZURE_CREDENTIALS }}

        - name: Azure CLI script file
          uses: azure/CLI@v1
          with:
            azcliversion: 2.30.0
            inlineScript: |
              az extension add --name containerapp
              az containerapp update \
                --name groupe4containerapp \
                --resource-group ${{ secrets.RESOURCE_GROUP }} 